plugins:
  encrypt_enabled:
    client: true
    default: true
    refresh: true
  auto_enable_encrypt:
    client: true
    default: false
    refresh: true
  encrypt_groups:
    default: ""
    client: true
    type: list
    list_type: simple
  encrypt_pms_default:
    client: true
    default: true
  require_time_bombs:
    client: true
    default: true
  required_time_bomb_length:
    client: true
    default: "3 minutes"
    type: enum
    choices:
      - "3 minutes"
      - "1 hour"
      - "3 hours"
      - "12 hours"
      - "24 hours"
      - "3 days"
      - "7 days"
